compile_pdf:
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  script:
    - lualatex cv-en.tex
    - biber cv-en
    - lualatex cv-en.tex
    - lualatex cv-en.tex    
  artifacts:
    paths:
      - cv-en.pdf
